import Head from 'next/head'

// const conn: WebSocket = new WebSocket('ws://localhost:7181/socket');

export default function Home() {
  // let peerConnection: RTCPeerConnection;
  //
  // const send = (message: { event: string, data: RTCIceCandidate, }) => conn.send(JSON.stringify(message));
  //
  // const initialize = () => {
  //   let configuration = null;
  //   peerConnection = new RTCPeerConnection(configuration);

    // Setup ice handling
    // peerConnection.onicecandidate = (ev) => {
    //   if (ev.candidate) send({
    //     event: 'candidate',
    //     data: ev.candidate,
    //   });
    // }

    // Creating data channel
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Lorem ipsum</div>
      </main>
    </>
  );
}
